# Generated by Django 6.0.5 on 2026-09-14 18:09

import apps.core.models
import apps.maps.validator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('width', models.PositiveSmallIntegerField(default=200, verbose_name='largura do mapa')),
                ('height', models.PositiveSmallIntegerField(default=200, verbose_name='altura do mapa')),
                ('order', models.PositiveSmallIntegerField(help_text='Posição no qual os andarems serão exibidos.', verbose_name='ordem')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.construction', verbose_name='construção')),
            ],
            options={
                'verbose_name': 'piso',
                'verbose_name_plural': 'pisos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.UniqueUUIDGenerator('maps', 'Room'), primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('svg_path', models.TextField(help_text="Valor do atributo 'd' do elemento <path>.", validators=[apps.maps.validator.SVGPathValidator()], verbose_name='SVG path')),
                ('svg_view_box', models.CharField(blank=True, help_text="Valor do atributo 'viewBox' (ex.: '0 0 1024 768').", max_length=64, validators=[apps.maps.validator.SVGViewBoxValidator()], verbose_name='SVG viewBox')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('description', models.TextField(db_index=True, max_length=256, verbose_name='descrição')),
                ('area', models.FloatField(help_text='Área em metros quádrados.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='área (m²)')),
                ('color', models.CharField(db_index=True, max_length=7, validators=[apps.maps.validator.validate_hex_color], verbose_name='cor')),
                ('position_x', models.FloatField(default=0.0, validators=[apps.maps.validator.validate_position], verbose_name='posição X')),
                ('position_y', models.FloatField(default=0.0, validators=[apps.maps.validator.validate_position], verbose_name='posição Y')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotação em graus (0-360).', validators=[apps.maps.validator.validate_rotation], verbose_name='rotação')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.floor', verbose_name='piso')),
            ],
            options={
                'verbose_name': 'cômodo',
                'verbose_name_plural': 'cômodos',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('construction', 'order'), name='unique_construction_order'),
        ),
    ]
