# Generated by Django 6.0.5 on 2026-09-10 21:27

import apps.core.models
import apps.core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', apps.core.models.CustomImageField(blank=True, height=288, null=True, subdir='uploads/images/contruction/photo/', upload_to=apps.core.utils.PathAndRename('uploads/images/contruction/photo/'), verbose_name='Foto', width=512)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('address', models.TextField(verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'Construção',
                'verbose_name_plural': 'Construções',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('codename', models.CharField(db_index=True, max_length=100, verbose_name='codinome')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.construction', verbose_name='construção')),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConstructionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.construction', verbose_name='construção')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para o grupo.', to='business.constructionpermission', verbose_name='permissões')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='funcionário está ativo')),
                ('is_admin', models.BooleanField(default=False, help_text='Designa que este funcionário tem todas as permissões da construção sem atribuí-las explicitamente', verbose_name='é administrador geral')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.construction', verbose_name='construção')),
                ('groups', models.ManyToManyField(blank=True, db_index=True, help_text='Grupos que o funcionário faz parte.', to='business.constructiongroup', verbose_name='grupos da construção')),
                ('permissions', models.ManyToManyField(blank=True, db_index=True, help_text='Permissões específicas para o funcionário.', to='business.constructionpermission', verbose_name='permissões da construção')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='constructionpermission',
            constraint=models.UniqueConstraint(fields=('construction', 'codename'), name='unique-construction_permission'),
        ),
        migrations.AddConstraint(
            model_name='constructiongroup',
            constraint=models.UniqueConstraint(fields=('construction', 'name'), name='unique-construction_name'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('construction', 'user'), name='unique-construction_user'),
        ),
    ]
