# Generated by Django 6.0.5 on 2026-07-14 22:03

import apps.constructions.validator
import apps.core.models
import apps.core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', apps.core.models.CustomImageField(blank=True, height=512, null=True, subdir='uploads/images/contruction/photo/', upload_to=apps.core.utils.PathAndRename('uploads/images/contruction/photo/'), verbose_name='Foto', width=512)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('address', models.TextField(db_index=True, verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'Construção',
                'verbose_name_plural': 'Construções',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.construction', verbose_name='construção')),
            ],
            options={
                'verbose_name': 'piso',
                'verbose_name_plural': 'pisos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.UniqueUUIDGenerator('constructions', 'Room'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('svg_path', models.TextField(help_text="Valor do atributo 'd' do elemento <path>.", validators=[apps.constructions.validator.SVGPathValidator()], verbose_name='SVG path')),
                ('svg_view_box', models.CharField(blank=True, help_text="Valor do atributo 'viewBox' (ex.: '0 0 1024 768').", max_length=64, validators=[apps.constructions.validator.SVGViewBoxValidator()], verbose_name='SVG viewBox')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nome')),
                ('description', models.TextField(db_index=True, max_length=256, verbose_name='descrição')),
                ('area', models.FloatField(help_text='Área em metros quádrados.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='área (m²)')),
                ('color', models.CharField(db_index=True, max_length=7, validators=[apps.constructions.validator.validate_hex_color], verbose_name='cor')),
                ('position_x', models.FloatField(default=0.0, validators=[apps.constructions.validator.validate_position], verbose_name='posição X')),
                ('position_y', models.FloatField(default=0.0, validators=[apps.constructions.validator.validate_position], verbose_name='posição Y')),
                ('rotation', models.FloatField(default=0.0, help_text='Rotação em graus (0-360).', validators=[apps.constructions.validator.validate_rotation], verbose_name='rotação')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.floor', verbose_name='piso')),
            ],
            options={
                'verbose_name': 'cômodo',
                'verbose_name_plural': 'cômodos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.construction', verbose_name='construção')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('construction', 'user'), name='unique_employee')],
            },
        ),
    ]
